home:
    pattern: /
    defaults: { _controller: AppBundle:Default:index }
    options:
        expose: true

produit:
    pattern: /produit:{id}
    defaults: { _controller: AppBundle:Default:produit }
    options:
        expose: true

home:
    pattern: /panier
    defaults: { _controller: AppBundle:Default:panier }
    options:
        expose: true